// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mycel/registry/subdomain_config.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubdomainRegistrationFees struct {
	FeeByLength map[uint32]*Fee `protobuf:"bytes,1,rep,name=feeByLength,proto3" json:"feeByLength,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FeeByName   map[string]*Fee `protobuf:"bytes,2,rep,name=feeByName,proto3" json:"feeByName,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DefaultFee  *types.Coin     `protobuf:"bytes,3,opt,name=defaultFee,proto3" json:"defaultFee,omitempty"`
}

func (m *SubdomainRegistrationFees) Reset()         { *m = SubdomainRegistrationFees{} }
func (m *SubdomainRegistrationFees) String() string { return proto.CompactTextString(m) }
func (*SubdomainRegistrationFees) ProtoMessage()    {}
func (*SubdomainRegistrationFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e8e4d1516ffeeb, []int{0}
}
func (m *SubdomainRegistrationFees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubdomainRegistrationFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubdomainRegistrationFees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubdomainRegistrationFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubdomainRegistrationFees.Merge(m, src)
}
func (m *SubdomainRegistrationFees) XXX_Size() int {
	return m.Size()
}
func (m *SubdomainRegistrationFees) XXX_DiscardUnknown() {
	xxx_messageInfo_SubdomainRegistrationFees.DiscardUnknown(m)
}

var xxx_messageInfo_SubdomainRegistrationFees proto.InternalMessageInfo

func (m *SubdomainRegistrationFees) GetFeeByLength() map[uint32]*Fee {
	if m != nil {
		return m.FeeByLength
	}
	return nil
}

func (m *SubdomainRegistrationFees) GetFeeByName() map[string]*Fee {
	if m != nil {
		return m.FeeByName
	}
	return nil
}

func (m *SubdomainRegistrationFees) GetDefaultFee() *types.Coin {
	if m != nil {
		return m.DefaultFee
	}
	return nil
}

type Fee struct {
	IsRegistrable bool        `protobuf:"varint,1,opt,name=isRegistrable,proto3" json:"isRegistrable,omitempty"`
	Fee           *types.Coin `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (m *Fee) Reset()         { *m = Fee{} }
func (m *Fee) String() string { return proto.CompactTextString(m) }
func (*Fee) ProtoMessage()    {}
func (*Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e8e4d1516ffeeb, []int{1}
}
func (m *Fee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fee.Merge(m, src)
}
func (m *Fee) XXX_Size() int {
	return m.Size()
}
func (m *Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_Fee proto.InternalMessageInfo

func (m *Fee) GetIsRegistrable() bool {
	if m != nil {
		return m.IsRegistrable
	}
	return false
}

func (m *Fee) GetFee() *types.Coin {
	if m != nil {
		return m.Fee
	}
	return nil
}

type SubdomainConfig struct {
	MaxSubdomainRegistrations uint64                     `protobuf:"varint,1,opt,name=maxSubdomainRegistrations,proto3" json:"maxSubdomainRegistrations,omitempty"`
	SubdomainRegistrationFees *SubdomainRegistrationFees `protobuf:"bytes,2,opt,name=subdomainRegistrationFees,proto3" json:"subdomainRegistrationFees,omitempty"`
}

func (m *SubdomainConfig) Reset()         { *m = SubdomainConfig{} }
func (m *SubdomainConfig) String() string { return proto.CompactTextString(m) }
func (*SubdomainConfig) ProtoMessage()    {}
func (*SubdomainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e8e4d1516ffeeb, []int{2}
}
func (m *SubdomainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubdomainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubdomainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubdomainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubdomainConfig.Merge(m, src)
}
func (m *SubdomainConfig) XXX_Size() int {
	return m.Size()
}
func (m *SubdomainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SubdomainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SubdomainConfig proto.InternalMessageInfo

func (m *SubdomainConfig) GetMaxSubdomainRegistrations() uint64 {
	if m != nil {
		return m.MaxSubdomainRegistrations
	}
	return 0
}

func (m *SubdomainConfig) GetSubdomainRegistrationFees() *SubdomainRegistrationFees {
	if m != nil {
		return m.SubdomainRegistrationFees
	}
	return nil
}

func init() {
	proto.RegisterType((*SubdomainRegistrationFees)(nil), "mycel.registry.SubdomainRegistrationFees")
	proto.RegisterMapType((map[uint32]*Fee)(nil), "mycel.registry.SubdomainRegistrationFees.FeeByLengthEntry")
	proto.RegisterMapType((map[string]*Fee)(nil), "mycel.registry.SubdomainRegistrationFees.FeeByNameEntry")
	proto.RegisterType((*Fee)(nil), "mycel.registry.Fee")
	proto.RegisterType((*SubdomainConfig)(nil), "mycel.registry.SubdomainConfig")
}

func init() {
	proto.RegisterFile("mycel/registry/subdomain_config.proto", fileDescriptor_a1e8e4d1516ffeeb)
}

var fileDescriptor_a1e8e4d1516ffeeb = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x6b, 0xd4, 0x40,
	0x18, 0xc6, 0x77, 0x1a, 0x15, 0xfb, 0x2e, 0xad, 0x65, 0xbc, 0x24, 0x7b, 0x08, 0xcb, 0xa2, 0xb0,
	0x45, 0x9c, 0xd0, 0x7a, 0xa9, 0xc5, 0x53, 0x8b, 0xc1, 0x83, 0x08, 0x4e, 0x41, 0x44, 0x04, 0x99,
	0xa4, 0x6f, 0xd2, 0xc1, 0x24, 0x53, 0x32, 0x93, 0xd2, 0x7c, 0x0b, 0x3f, 0x8c, 0x07, 0x3f, 0x82,
	0xc7, 0x1e, 0x3d, 0xca, 0xee, 0x17, 0x91, 0x4c, 0x36, 0xee, 0x1f, 0x8c, 0x68, 0x6f, 0x99, 0xf0,
	0x3c, 0xbf, 0xf7, 0xe1, 0x79, 0x67, 0xe0, 0x71, 0x5e, 0xc7, 0x98, 0x05, 0x25, 0xa6, 0x52, 0x9b,
	0xb2, 0x0e, 0x74, 0x15, 0x9d, 0xab, 0x5c, 0xc8, 0xe2, 0x53, 0xac, 0x8a, 0x44, 0xa6, 0xec, 0xb2,
	0x54, 0x46, 0xd1, 0x5d, 0x2b, 0x63, 0x9d, 0x6c, 0xe4, 0xc7, 0x4a, 0xe7, 0x4a, 0x07, 0x91, 0xd0,
	0x18, 0x5c, 0x1d, 0x44, 0x68, 0xc4, 0x41, 0x10, 0x2b, 0x59, 0xb4, 0xfa, 0xc9, 0x57, 0x07, 0xbc,
	0xb3, 0x0e, 0xc5, 0x5b, 0x97, 0x30, 0x52, 0x15, 0x21, 0xa2, 0xa6, 0x1f, 0x61, 0x98, 0x20, 0x9e,
	0xd4, 0xaf, 0xb1, 0x48, 0xcd, 0x85, 0x4b, 0xc6, 0xce, 0x74, 0x78, 0x78, 0xcc, 0xd6, 0x67, 0xb0,
	0x5e, 0x3f, 0x0b, 0x97, 0xe6, 0x97, 0x85, 0x29, 0x6b, 0xbe, 0x8a, 0xa3, 0xef, 0x60, 0xdb, 0x1e,
	0xdf, 0x88, 0x1c, 0xdd, 0x2d, 0xcb, 0x3e, 0xfa, 0x4f, 0x76, 0x63, 0x6d, 0xc9, 0x4b, 0x14, 0x7d,
	0x0e, 0x70, 0x8e, 0x89, 0xa8, 0x32, 0x13, 0x22, 0xba, 0xce, 0x98, 0x4c, 0x87, 0x87, 0x1e, 0x6b,
	0x8b, 0x60, 0x4d, 0x11, 0x6c, 0x51, 0x04, 0x3b, 0x55, 0xb2, 0xe0, 0x2b, 0xe2, 0xd1, 0x19, 0xec,
	0x6d, 0x66, 0xa6, 0x7b, 0xe0, 0x7c, 0xc6, 0xda, 0x25, 0x63, 0x32, 0xdd, 0xe1, 0xcd, 0x27, 0xdd,
	0x87, 0xbb, 0x57, 0x22, 0xab, 0x9a, 0xd0, 0x0d, 0xfb, 0xe1, 0x66, 0xe8, 0x10, 0x91, 0xb7, 0x8a,
	0xe3, 0xad, 0x23, 0x32, 0x7a, 0x0b, 0xbb, 0xeb, 0x61, 0x57, 0x91, 0xdb, 0xb7, 0x41, 0x4e, 0xde,
	0x83, 0x13, 0x22, 0xd2, 0x47, 0xb0, 0x23, 0x75, 0xd7, 0x4c, 0x94, 0xa1, 0x25, 0xde, 0xe7, 0xeb,
	0x3f, 0xe9, 0x13, 0x70, 0x12, 0xec, 0xc8, 0x7f, 0x29, 0xa2, 0x51, 0x4d, 0xbe, 0x11, 0x78, 0xf0,
	0xbb, 0xf4, 0x53, 0x7b, 0xb5, 0xe8, 0x0b, 0xf0, 0x72, 0x71, 0xfd, 0xc7, 0x55, 0x68, 0x3b, 0xf2,
	0x0e, 0xef, 0x17, 0xd0, 0x14, 0x3c, 0xdd, 0xb7, 0xc5, 0x45, 0xa8, 0xfd, 0x7f, 0x5e, 0x3b, 0xef,
	0x67, 0x9d, 0xbc, 0xfa, 0x3e, 0xf3, 0xc9, 0xcd, 0xcc, 0x27, 0x3f, 0x67, 0x3e, 0xf9, 0x32, 0xf7,
	0x07, 0x37, 0x73, 0x7f, 0xf0, 0x63, 0xee, 0x0f, 0x3e, 0xb0, 0x54, 0x9a, 0x8b, 0x2a, 0x62, 0xb1,
	0xca, 0x03, 0x3b, 0xe9, 0x69, 0x8b, 0x68, 0x0f, 0xc1, 0xf5, 0xf2, 0x59, 0x99, 0xfa, 0x12, 0x75,
	0x74, 0xcf, 0x3e, 0x8e, 0x67, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xb2, 0x08, 0xd7, 0x75,
	0x03, 0x00, 0x00,
}

func (m *SubdomainRegistrationFees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubdomainRegistrationFees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubdomainRegistrationFees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DefaultFee != nil {
		{
			size, err := m.DefaultFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSubdomainConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FeeByName) > 0 {
		for k := range m.FeeByName {
			v := m.FeeByName[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintSubdomainConfig(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintSubdomainConfig(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintSubdomainConfig(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.FeeByLength) > 0 {
		for k := range m.FeeByLength {
			v := m.FeeByLength[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintSubdomainConfig(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintSubdomainConfig(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintSubdomainConfig(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Fee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Fee != nil {
		{
			size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSubdomainConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.IsRegistrable {
		i--
		if m.IsRegistrable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubdomainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubdomainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubdomainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubdomainRegistrationFees != nil {
		{
			size, err := m.SubdomainRegistrationFees.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSubdomainConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.MaxSubdomainRegistrations != 0 {
		i = encodeVarintSubdomainConfig(dAtA, i, uint64(m.MaxSubdomainRegistrations))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSubdomainConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovSubdomainConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubdomainRegistrationFees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FeeByLength) > 0 {
		for k, v := range m.FeeByLength {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovSubdomainConfig(uint64(l))
			}
			mapEntrySize := 1 + sovSubdomainConfig(uint64(k)) + l
			n += mapEntrySize + 1 + sovSubdomainConfig(uint64(mapEntrySize))
		}
	}
	if len(m.FeeByName) > 0 {
		for k, v := range m.FeeByName {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovSubdomainConfig(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovSubdomainConfig(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovSubdomainConfig(uint64(mapEntrySize))
		}
	}
	if m.DefaultFee != nil {
		l = m.DefaultFee.Size()
		n += 1 + l + sovSubdomainConfig(uint64(l))
	}
	return n
}

func (m *Fee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsRegistrable {
		n += 2
	}
	if m.Fee != nil {
		l = m.Fee.Size()
		n += 1 + l + sovSubdomainConfig(uint64(l))
	}
	return n
}

func (m *SubdomainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxSubdomainRegistrations != 0 {
		n += 1 + sovSubdomainConfig(uint64(m.MaxSubdomainRegistrations))
	}
	if m.SubdomainRegistrationFees != nil {
		l = m.SubdomainRegistrationFees.Size()
		n += 1 + l + sovSubdomainConfig(uint64(l))
	}
	return n
}

func sovSubdomainConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSubdomainConfig(x uint64) (n int) {
	return sovSubdomainConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubdomainRegistrationFees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubdomainConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubdomainRegistrationFees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubdomainRegistrationFees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeByLength", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FeeByLength == nil {
				m.FeeByLength = make(map[uint32]*Fee)
			}
			var mapkey uint32
			var mapvalue *Fee
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSubdomainConfig
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSubdomainConfig
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSubdomainConfig
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Fee{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSubdomainConfig(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.FeeByLength[mapkey] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeByName", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FeeByName == nil {
				m.FeeByName = make(map[string]*Fee)
			}
			var mapkey string
			var mapvalue *Fee
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSubdomainConfig
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSubdomainConfig
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSubdomainConfig
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Fee{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSubdomainConfig(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthSubdomainConfig
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.FeeByName[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DefaultFee == nil {
				m.DefaultFee = &types.Coin{}
			}
			if err := m.DefaultFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSubdomainConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubdomainConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRegistrable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsRegistrable = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fee == nil {
				m.Fee = &types.Coin{}
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSubdomainConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubdomainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubdomainConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubdomainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubdomainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSubdomainRegistrations", wireType)
			}
			m.MaxSubdomainRegistrations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSubdomainRegistrations |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubdomainRegistrationFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SubdomainRegistrationFees == nil {
				m.SubdomainRegistrationFees = &SubdomainRegistrationFees{}
			}
			if err := m.SubdomainRegistrationFees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSubdomainConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubdomainConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSubdomainConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSubdomainConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubdomainConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSubdomainConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSubdomainConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSubdomainConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSubdomainConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSubdomainConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSubdomainConfig = fmt.Errorf("proto: unexpected end of group")
)
