// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mycel/mycel/domain.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DNSRecordType int32

const (
	DNSRecordType_A     DNSRecordType = 0
	DNSRecordType_AAAA  DNSRecordType = 1
	DNSRecordType_CNAME DNSRecordType = 2
	DNSRecordType_NS    DNSRecordType = 3
	DNSRecordType_MX    DNSRecordType = 4
	DNSRecordType_PTR   DNSRecordType = 5
	DNSRecordType_SOA   DNSRecordType = 6
	DNSRecordType_SRV   DNSRecordType = 7
	DNSRecordType_TXT   DNSRecordType = 8
)

var DNSRecordType_name = map[int32]string{
	0: "A",
	1: "AAAA",
	2: "CNAME",
	3: "NS",
	4: "MX",
	5: "PTR",
	6: "SOA",
	7: "SRV",
	8: "TXT",
}

var DNSRecordType_value = map[string]int32{
	"A":     0,
	"AAAA":  1,
	"CNAME": 2,
	"NS":    3,
	"MX":    4,
	"PTR":   5,
	"SOA":   6,
	"SRV":   7,
	"TXT":   8,
}

func (x DNSRecordType) String() string {
	return proto.EnumName(DNSRecordType_name, int32(x))
}

func (DNSRecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_91aa379aa9574c23, []int{0}
}

type WalletRecordType int32

const (
	WalletRecordType_ETHEREUM_MAINNET WalletRecordType = 0
	WalletRecordType_ETHEREUM_GOERLI  WalletRecordType = 1
	WalletRecordType_POLYGON_MAINNET  WalletRecordType = 2
	WalletRecordType_POLYGON_MUMBAI   WalletRecordType = 3
)

var WalletRecordType_name = map[int32]string{
	0: "ETHEREUM_MAINNET",
	1: "ETHEREUM_GOERLI",
	2: "POLYGON_MAINNET",
	3: "POLYGON_MUMBAI",
}

var WalletRecordType_value = map[string]int32{
	"ETHEREUM_MAINNET": 0,
	"ETHEREUM_GOERLI":  1,
	"POLYGON_MAINNET":  2,
	"POLYGON_MUMBAI":   3,
}

func (x WalletRecordType) String() string {
	return proto.EnumName(WalletRecordType_name, int32(x))
}

func (WalletRecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_91aa379aa9574c23, []int{1}
}

type WalletAddressFormat int32

const (
	WalletAddressFormat_ETHEREUM WalletAddressFormat = 0
	WalletAddressFormat_IBC      WalletAddressFormat = 1
)

var WalletAddressFormat_name = map[int32]string{
	0: "ETHEREUM",
	1: "IBC",
}

var WalletAddressFormat_value = map[string]int32{
	"ETHEREUM": 0,
	"IBC":      1,
}

func (x WalletAddressFormat) String() string {
	return proto.EnumName(WalletAddressFormat_name, int32(x))
}

func (WalletAddressFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_91aa379aa9574c23, []int{2}
}

type DNSRecord struct {
	DNSRecordType DNSRecordType     `protobuf:"varint,1,opt,name=DNSRecordType,proto3,enum=mycel.mycel.DNSRecordType" json:"DNSRecordType,omitempty"`
	Value         string            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *DNSRecord) Reset()         { *m = DNSRecord{} }
func (m *DNSRecord) String() string { return proto.CompactTextString(m) }
func (*DNSRecord) ProtoMessage()    {}
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_91aa379aa9574c23, []int{0}
}
func (m *DNSRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DNSRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DNSRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DNSRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSRecord.Merge(m, src)
}
func (m *DNSRecord) XXX_Size() int {
	return m.Size()
}
func (m *DNSRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DNSRecord proto.InternalMessageInfo

func (m *DNSRecord) GetDNSRecordType() DNSRecordType {
	if m != nil {
		return m.DNSRecordType
	}
	return DNSRecordType_A
}

func (m *DNSRecord) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DNSRecord) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type WalletRecord struct {
	WalletRecordType    WalletRecordType    `protobuf:"varint,1,opt,name=walletRecordType,proto3,enum=mycel.mycel.WalletRecordType" json:"walletRecordType,omitempty"`
	WalletAddressFormat WalletAddressFormat `protobuf:"varint,2,opt,name=WalletAddressFormat,proto3,enum=mycel.mycel.WalletAddressFormat" json:"WalletAddressFormat,omitempty"`
	Value               string              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Metadata            map[string]string   `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *WalletRecord) Reset()         { *m = WalletRecord{} }
func (m *WalletRecord) String() string { return proto.CompactTextString(m) }
func (*WalletRecord) ProtoMessage()    {}
func (*WalletRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_91aa379aa9574c23, []int{1}
}
func (m *WalletRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WalletRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WalletRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WalletRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletRecord.Merge(m, src)
}
func (m *WalletRecord) XXX_Size() int {
	return m.Size()
}
func (m *WalletRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletRecord.DiscardUnknown(m)
}

var xxx_messageInfo_WalletRecord proto.InternalMessageInfo

func (m *WalletRecord) GetWalletRecordType() WalletRecordType {
	if m != nil {
		return m.WalletRecordType
	}
	return WalletRecordType_ETHEREUM_MAINNET
}

func (m *WalletRecord) GetWalletAddressFormat() WalletAddressFormat {
	if m != nil {
		return m.WalletAddressFormat
	}
	return WalletAddressFormat_ETHEREUM
}

func (m *WalletRecord) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *WalletRecord) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Domain struct {
	Name           string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner          string                   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ExpirationDate int64                    `protobuf:"varint,3,opt,name=expirationDate,proto3" json:"expirationDate,omitempty"`
	Parent         string                   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	DNSRecords     map[string]*DNSRecord    `protobuf:"bytes,5,rep,name=DNSRecords,proto3" json:"DNSRecords,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	WalletRecords  map[string]*WalletRecord `protobuf:"bytes,6,rep,name=walletRecords,proto3" json:"walletRecords,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metadata       map[string]string        `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_91aa379aa9574c23, []int{2}
}
func (m *Domain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return m.Size()
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Domain) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Domain) GetExpirationDate() int64 {
	if m != nil {
		return m.ExpirationDate
	}
	return 0
}

func (m *Domain) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Domain) GetDNSRecords() map[string]*DNSRecord {
	if m != nil {
		return m.DNSRecords
	}
	return nil
}

func (m *Domain) GetWalletRecords() map[string]*WalletRecord {
	if m != nil {
		return m.WalletRecords
	}
	return nil
}

func (m *Domain) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("mycel.mycel.DNSRecordType", DNSRecordType_name, DNSRecordType_value)
	proto.RegisterEnum("mycel.mycel.WalletRecordType", WalletRecordType_name, WalletRecordType_value)
	proto.RegisterEnum("mycel.mycel.WalletAddressFormat", WalletAddressFormat_name, WalletAddressFormat_value)
	proto.RegisterType((*DNSRecord)(nil), "mycel.mycel.DNSRecord")
	proto.RegisterMapType((map[string]string)(nil), "mycel.mycel.DNSRecord.MetadataEntry")
	proto.RegisterType((*WalletRecord)(nil), "mycel.mycel.WalletRecord")
	proto.RegisterMapType((map[string]string)(nil), "mycel.mycel.WalletRecord.MetadataEntry")
	proto.RegisterType((*Domain)(nil), "mycel.mycel.Domain")
	proto.RegisterMapType((map[string]*DNSRecord)(nil), "mycel.mycel.Domain.DNSRecordsEntry")
	proto.RegisterMapType((map[string]string)(nil), "mycel.mycel.Domain.MetadataEntry")
	proto.RegisterMapType((map[string]*WalletRecord)(nil), "mycel.mycel.Domain.WalletRecordsEntry")
}

func init() { proto.RegisterFile("mycel/mycel/domain.proto", fileDescriptor_91aa379aa9574c23) }

var fileDescriptor_91aa379aa9574c23 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x5f, 0x4f, 0xd3, 0x50,
	0x14, 0xdf, 0x5d, 0xbb, 0xb2, 0x1d, 0x60, 0xdc, 0x1c, 0x08, 0xa9, 0x24, 0x36, 0x13, 0x0d, 0x12,
	0x82, 0x23, 0x99, 0x2f, 0x46, 0x63, 0x42, 0x19, 0x15, 0x97, 0xd0, 0x8e, 0x5c, 0x8a, 0xa0, 0x3e,
	0x90, 0xca, 0xae, 0x09, 0x71, 0x6b, 0x97, 0xae, 0x0a, 0xfb, 0x16, 0x7e, 0x19, 0x3f, 0x82, 0x89,
	0x8f, 0x3c, 0xfa, 0x68, 0xc6, 0x17, 0x31, 0xbd, 0x2d, 0xe5, 0x76, 0x94, 0x27, 0xe3, 0xcb, 0xdd,
	0x39, 0x67, 0xe7, 0xf7, 0xeb, 0xef, 0xfc, 0xb9, 0x17, 0xf4, 0xc1, 0xf8, 0x8c, 0xf7, 0xb7, 0x92,
	0xb3, 0x17, 0x0c, 0xbc, 0x73, 0xbf, 0x39, 0x0c, 0x83, 0x28, 0xc0, 0x59, 0x11, 0x6b, 0x8a, 0x73,
	0x75, 0x42, 0xa0, 0xb6, 0xeb, 0x1c, 0x32, 0x7e, 0x16, 0x84, 0x3d, 0xdc, 0x86, 0xf9, 0xcc, 0x71,
	0xc7, 0x43, 0xae, 0x93, 0x06, 0x59, 0xaf, 0xb7, 0x56, 0x9a, 0x12, 0xa4, 0x99, 0xcb, 0x60, 0x79,
	0x00, 0x2e, 0x41, 0xe5, 0x9b, 0xd7, 0xff, 0xca, 0xf5, 0x72, 0x83, 0xac, 0xd7, 0x58, 0xe2, 0xe0,
	0x36, 0x54, 0x07, 0x3c, 0xf2, 0x7a, 0x5e, 0xe4, 0xe9, 0x4a, 0x43, 0x59, 0x9f, 0x6d, 0x3d, 0x29,
	0xa6, 0x6c, 0xda, 0x69, 0x9a, 0xe5, 0x47, 0xe1, 0x98, 0x65, 0xa8, 0x95, 0x57, 0x30, 0x9f, 0xfb,
	0x0b, 0x29, 0x28, 0x5f, 0xf8, 0x58, 0x08, 0xac, 0xb1, 0xd8, 0x2c, 0xfe, 0xf4, 0xcb, 0xf2, 0x0b,
	0xb2, 0xfa, 0xb3, 0x0c, 0x73, 0xc7, 0x5e, 0xbf, 0xcf, 0xa3, 0xb4, 0xce, 0x0e, 0xd0, 0x0b, 0xc9,
	0x97, 0x4a, 0x7d, 0x98, 0xd3, 0x75, 0x3c, 0x95, 0xc4, 0xee, 0xc0, 0x90, 0xc1, 0x62, 0x92, 0x65,
	0xf6, 0x7a, 0x21, 0x1f, 0x8d, 0xde, 0x04, 0xe1, 0xc0, 0x8b, 0x84, 0x86, 0x7a, 0xab, 0x51, 0xc0,
	0x96, 0xcb, 0x63, 0x45, 0xe0, 0xdb, 0x4a, 0x14, 0xb9, 0x89, 0x6d, 0xa9, 0x89, 0xaa, 0x68, 0xe2,
	0xd3, 0x7b, 0xc5, 0xfe, 0x9f, 0x3e, 0xfe, 0x50, 0x41, 0xdb, 0x15, 0xab, 0x84, 0x08, 0xaa, 0xef,
	0x0d, 0x78, 0x8a, 0x13, 0x76, 0x0c, 0x0c, 0x2e, 0x7c, 0x1e, 0xde, 0x00, 0x85, 0x83, 0x6b, 0x50,
	0xe7, 0x97, 0xc3, 0xf3, 0xd0, 0x8b, 0xce, 0x03, 0x7f, 0xd7, 0x8b, 0x92, 0xaa, 0x14, 0x36, 0x15,
	0xc5, 0x65, 0xd0, 0x86, 0x5e, 0xc8, 0xfd, 0x48, 0x57, 0x05, 0x3c, 0xf5, 0xb0, 0x0d, 0x90, 0xad,
	0xc7, 0x48, 0xaf, 0x88, 0xc2, 0x1f, 0xe7, 0xb7, 0x27, 0xd9, 0xee, 0xdb, 0xac, 0xa4, 0x68, 0x09,
	0x86, 0xfb, 0x30, 0x2f, 0x4f, 0x6e, 0xa4, 0x6b, 0x82, 0x67, 0xad, 0x88, 0x47, 0xee, 0x63, 0x4a,
	0x95, 0x07, 0xe3, 0x6b, 0x69, 0x12, 0x33, 0x82, 0xe8, 0x51, 0x11, 0xd1, 0x7d, 0x33, 0x38, 0x82,
	0x85, 0x29, 0xad, 0x05, 0x53, 0xd8, 0x94, 0xa7, 0x30, 0xdb, 0x5a, 0x2e, 0xbe, 0x2f, 0xd2, 0x74,
	0x56, 0x3e, 0x02, 0xde, 0x95, 0x5e, 0xc0, 0xbc, 0x95, 0x67, 0x7e, 0x70, 0xef, 0x12, 0xc9, 0xe4,
	0xff, 0xb2, 0x37, 0x1b, 0xa7, 0x53, 0xcf, 0x0a, 0x56, 0x80, 0x98, 0xb4, 0x84, 0x55, 0x50, 0x4d,
	0xd3, 0x34, 0x29, 0xc1, 0x1a, 0x54, 0xda, 0x8e, 0x69, 0x5b, 0xb4, 0x8c, 0x1a, 0x94, 0x9d, 0x43,
	0xaa, 0xc4, 0xbf, 0xf6, 0x09, 0x55, 0x71, 0x06, 0x94, 0x03, 0x97, 0xd1, 0x4a, 0x6c, 0x1c, 0x76,
	0x4d, 0xaa, 0x09, 0x83, 0xbd, 0xa3, 0x33, 0xb1, 0xe1, 0x9e, 0xb8, 0xb4, 0xba, 0xf1, 0x19, 0xe8,
	0xf4, 0x55, 0xc5, 0x25, 0xa0, 0x96, 0xfb, 0xd6, 0x62, 0xd6, 0x91, 0x7d, 0x6a, 0x9b, 0x1d, 0xc7,
	0xb1, 0x5c, 0x5a, 0xc2, 0x45, 0x58, 0xc8, 0xa2, 0x7b, 0x5d, 0x8b, 0xed, 0x77, 0x28, 0x89, 0x83,
	0x07, 0xdd, 0xfd, 0xf7, 0x7b, 0x5d, 0x27, 0xcb, 0x2c, 0x23, 0x42, 0x3d, 0x0b, 0x1e, 0xd9, 0x3b,
	0x66, 0x87, 0x2a, 0x1b, 0x9b, 0x85, 0x97, 0x1d, 0xe7, 0xa0, 0x7a, 0x43, 0x4a, 0x4b, 0xb1, 0xaa,
	0xce, 0x4e, 0x9b, 0x92, 0x9d, 0x67, 0xbf, 0x26, 0x06, 0xb9, 0x9a, 0x18, 0xe4, 0xcf, 0xc4, 0x20,
	0xdf, 0xaf, 0x8d, 0xd2, 0xd5, 0xb5, 0x51, 0xfa, 0x7d, 0x6d, 0x94, 0x3e, 0x2c, 0x26, 0xcf, 0xf2,
	0x65, 0xfa, 0x3c, 0x47, 0xe3, 0x21, 0x1f, 0x7d, 0xd2, 0xc4, 0xf3, 0xfc, 0xfc, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x13, 0x7d, 0x0d, 0x36, 0xba, 0x05, 0x00, 0x00,
}

func (m *DNSRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DNSRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DNSRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintDomain(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintDomain(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintDomain(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintDomain(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if m.DNSRecordType != 0 {
		i = encodeVarintDomain(dAtA, i, uint64(m.DNSRecordType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *WalletRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WalletRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WalletRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintDomain(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintDomain(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintDomain(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintDomain(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if m.WalletAddressFormat != 0 {
		i = encodeVarintDomain(dAtA, i, uint64(m.WalletAddressFormat))
		i--
		dAtA[i] = 0x10
	}
	if m.WalletRecordType != 0 {
		i = encodeVarintDomain(dAtA, i, uint64(m.WalletRecordType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Domain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Domain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Domain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintDomain(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintDomain(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintDomain(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.WalletRecords) > 0 {
		for k := range m.WalletRecords {
			v := m.WalletRecords[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintDomain(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintDomain(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintDomain(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.DNSRecords) > 0 {
		for k := range m.DNSRecords {
			v := m.DNSRecords[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintDomain(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintDomain(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintDomain(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Parent) > 0 {
		i -= len(m.Parent)
		copy(dAtA[i:], m.Parent)
		i = encodeVarintDomain(dAtA, i, uint64(len(m.Parent)))
		i--
		dAtA[i] = 0x22
	}
	if m.ExpirationDate != 0 {
		i = encodeVarintDomain(dAtA, i, uint64(m.ExpirationDate))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintDomain(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintDomain(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDomain(dAtA []byte, offset int, v uint64) int {
	offset -= sovDomain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DNSRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DNSRecordType != 0 {
		n += 1 + sovDomain(uint64(m.DNSRecordType))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovDomain(uint64(l))
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovDomain(uint64(len(k))) + 1 + len(v) + sovDomain(uint64(len(v)))
			n += mapEntrySize + 1 + sovDomain(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *WalletRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WalletRecordType != 0 {
		n += 1 + sovDomain(uint64(m.WalletRecordType))
	}
	if m.WalletAddressFormat != 0 {
		n += 1 + sovDomain(uint64(m.WalletAddressFormat))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovDomain(uint64(l))
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovDomain(uint64(len(k))) + 1 + len(v) + sovDomain(uint64(len(v)))
			n += mapEntrySize + 1 + sovDomain(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *Domain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovDomain(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovDomain(uint64(l))
	}
	if m.ExpirationDate != 0 {
		n += 1 + sovDomain(uint64(m.ExpirationDate))
	}
	l = len(m.Parent)
	if l > 0 {
		n += 1 + l + sovDomain(uint64(l))
	}
	if len(m.DNSRecords) > 0 {
		for k, v := range m.DNSRecords {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovDomain(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovDomain(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovDomain(uint64(mapEntrySize))
		}
	}
	if len(m.WalletRecords) > 0 {
		for k, v := range m.WalletRecords {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovDomain(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovDomain(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovDomain(uint64(mapEntrySize))
		}
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovDomain(uint64(len(k))) + 1 + len(v) + sovDomain(uint64(len(v)))
			n += mapEntrySize + 1 + sovDomain(uint64(mapEntrySize))
		}
	}
	return n
}

func sovDomain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDomain(x uint64) (n int) {
	return sovDomain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DNSRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDomain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DNSRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DNSRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DNSRecordType", wireType)
			}
			m.DNSRecordType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DNSRecordType |= DNSRecordType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDomain
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDomain(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthDomain
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDomain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDomain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WalletRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDomain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WalletRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WalletRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletRecordType", wireType)
			}
			m.WalletRecordType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WalletRecordType |= WalletRecordType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAddressFormat", wireType)
			}
			m.WalletAddressFormat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WalletAddressFormat |= WalletAddressFormat(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDomain
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDomain(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthDomain
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDomain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDomain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Domain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDomain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Domain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Domain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpirationDate", wireType)
			}
			m.ExpirationDate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpirationDate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Parent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DNSRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DNSRecords == nil {
				m.DNSRecords = make(map[string]*DNSRecord)
			}
			var mapkey string
			var mapvalue *DNSRecord
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDomain
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthDomain
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthDomain
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &DNSRecord{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDomain(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthDomain
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.DNSRecords[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WalletRecords == nil {
				m.WalletRecords = make(map[string]*WalletRecord)
			}
			var mapkey string
			var mapvalue *WalletRecord
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDomain
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthDomain
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthDomain
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &WalletRecord{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDomain(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthDomain
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.WalletRecords[mapkey] = mapvalue
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDomain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDomain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDomain
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDomain
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthDomain
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthDomain
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDomain(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthDomain
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDomain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDomain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDomain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDomain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDomain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDomain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDomain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDomain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDomain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDomain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDomain = fmt.Errorf("proto: unexpected end of group")
)
